data_path = 'genArt'
image_size = (3, 64, 64)
batch_size = 32
add_noise = False
real_label = 1.0
fake_label = 0.0
fmsG = 128
fmsD = 128
adam_params_G = (0.0002, 0.9, 0.999)
adam_params_D = (0.0002, 0.9, 0.999)
lambda_gp = 10
latent_dim = 100
sample_interval = 500
n_epochs = 3000
load_models = False
path_g = ' '
path_d = ' '
########################################################################################################################
# data_path = directory where the training images are located
# image_size = desired size of images (must be (n, f, f), where n can be any positive number and f must be a power of 2
# batch_size = how many pictures are generated and the number of fake and real images the discrim sees before updating
# add_noise = do the real images have noise added to them before being given to the discrim (currently not functional)
# real_label = what does the discriminator want to output if it thinks an image is real
# fake_label = what does the discriminator want to output if it thinks an image is fake
# fmsG = number of feature maps in generator
# fmsD = number of feature maps in discriminator
# adam_params_G = the learning rate, beta1, and beta2 inputted into G's adam optimizer
# adam_params_D = the learning rate, beta1, and beta2 inputted into D's adam optimizer
# lambda_gp = how much the calculated gradient penalty is multiplied by
# sample_interval = how often a plot, model, and sample images are saved
# n_epochs = how many epochs to train before terminating
# load_models = if models are to be loaded in, set this as True; otherwise leave this as False
# path_g = the path and file where the information for the generator model is stored
# path_d = the path and file where the information for the discriminator model is stored
